// <auto-generated />
using System;
using CarInsurance.DataAccessV3.CarInsuranceDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarInsurance.DataAccessV3.Migrations
{
    [DbContext(typeof(CarInsuranceContextV3))]
    [Migration("20200914100527_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.BrokerPolicyTemplate", b =>
                {
                    b.Property<Guid>("BrokerReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarBrokerRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoverBrokerRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("date");

                    b.Property<bool>("TemplateReady")
                        .HasColumnType("bit");

                    b.HasKey("BrokerReferenceId");

                    b.ToTable("BrokerPolicyTemplate");
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<Guid>("CarBrokerRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarRuleCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("EngineCC")
                        .HasColumnType("smallint");

                    b.Property<string>("EuroStandard")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime>("Year")
                        .HasColumnType("date");

                    b.HasKey("CarId");

                    b.HasIndex("CarBrokerRefId");

                    b.ToTable("Car");

                    b.HasCheckConstraint("constraint_euroStandard", "`EuroStandard` in ('Euro1','Euro2','Euro3','Euro4','Euro5','Euro6')");

                    b.HasCheckConstraint("constraint_carBrand", "`Brand` in ('volkswagen','bmw','mercedes-benz','opel','dacia','renault','toyota','skoda')");

                    b.HasCheckConstraint("constraint_carEngine", "`EngineCC` > 1000 and `EngineCC` < 5000");

                    b.HasCheckConstraint("constraint_carMode", "`Model` in ('octavia','rapid','fabia','passat','golf','c200','e200','c220','e220','320d','325d','330d','530d','520d','525d','astra','corsa','megane','clio','logan','sandero','avensis','prius')");
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.CarRule", b =>
                {
                    b.Property<int>("CarRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CarRuleCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<double>("Multiplier")
                        .HasColumnType("float(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CarRuleId");

                    b.HasIndex("CarRuleCoverId");

                    b.ToTable("CarRule");
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.Cover", b =>
                {
                    b.Property<int>("CoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AdditionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CoverBrokerRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LimitCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("CoverId");

                    b.HasIndex("CoverBrokerRefId");

                    b.ToTable("Cover");

                    b.HasCheckConstraint("constraint_coverType", "`Type` in ('theft','accidents','naturalhazard')");
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.Limit", b =>
                {
                    b.Property<int>("LimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverType")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<Guid>("LimitCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LimitRuleCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LimitValues")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("LimitId");

                    b.HasIndex("LimitCoverId");

                    b.ToTable("Limit");
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.LimitRule", b =>
                {
                    b.Property<int>("LimitRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("LimitRuleCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Multiplier")
                        .HasColumnType("float(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("RuleText")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("LimitRuleId");

                    b.HasIndex("LimitRuleCoverId");

                    b.ToTable("LimitRule");
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverType")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<Guid>("QuestionCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionRuleCoverId")
                        .HasColumnType("uniqueidentifier")
                        .IsUnicode(false);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionCoverId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.QuestionRule", b =>
                {
                    b.Property<int>("QuestionRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Multiplier")
                        .HasColumnType("float(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<Guid>("QuestionRuleCoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleText")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("QuestionRuleId");

                    b.HasIndex("QuestionRuleCoverId")
                        .IsUnique();

                    b.ToTable("QuestionRule");
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.Car", b =>
                {
                    b.HasOne("CarInsurance.DataAccessV3.DbModels.BrokerPolicyTemplate", "BrokerPolicyTemplate")
                        .WithMany("Car")
                        .HasForeignKey("CarBrokerRefId")
                        .HasConstraintName("FK_CarType")
                        .HasPrincipalKey("CarBrokerRefId")
                        .IsRequired();
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.CarRule", b =>
                {
                    b.HasOne("CarInsurance.DataAccessV3.DbModels.Car", "Car")
                        .WithMany("CarRule")
                        .HasForeignKey("CarRuleCoverId")
                        .HasConstraintName("FK_CarRuleType")
                        .HasPrincipalKey("CarRuleCoverId")
                        .IsRequired();
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.Cover", b =>
                {
                    b.HasOne("CarInsurance.DataAccessV3.DbModels.BrokerPolicyTemplate", "BrokerPolicyTemplate")
                        .WithMany("Cover")
                        .HasForeignKey("CoverBrokerRefId")
                        .HasConstraintName("FK_CoverType")
                        .HasPrincipalKey("CoverBrokerRefId")
                        .IsRequired();
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.Limit", b =>
                {
                    b.HasOne("CarInsurance.DataAccessV3.DbModels.Cover", "Cover")
                        .WithMany("Limit")
                        .HasForeignKey("LimitCoverId")
                        .HasConstraintName("FK_LimitType")
                        .HasPrincipalKey("LimitCoverId")
                        .IsRequired();
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.LimitRule", b =>
                {
                    b.HasOne("CarInsurance.DataAccessV3.DbModels.Limit", "Limit")
                        .WithMany("LimitRule")
                        .HasForeignKey("LimitRuleCoverId")
                        .HasConstraintName("FK_LimitRuleType")
                        .HasPrincipalKey("LimitRuleCoverId")
                        .IsRequired();
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.Question", b =>
                {
                    b.HasOne("CarInsurance.DataAccessV3.DbModels.Cover", "Cover")
                        .WithMany("Question")
                        .HasForeignKey("QuestionCoverId")
                        .HasConstraintName("FK_QuestionType")
                        .HasPrincipalKey("QuestionCoverId")
                        .IsRequired();
                });

            modelBuilder.Entity("CarInsurance.DataAccessV3.DbModels.QuestionRule", b =>
                {
                    b.HasOne("CarInsurance.DataAccessV3.DbModels.Question", "Question")
                        .WithOne("QuestionRule")
                        .HasForeignKey("CarInsurance.DataAccessV3.DbModels.QuestionRule", "QuestionRuleCoverId")
                        .HasConstraintName("FK_QuestionRuleType")
                        .HasPrincipalKey("CarInsurance.DataAccessV3.DbModels.Question", "QuestionRuleCoverId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
